INSERT INTO BOOKING_SYSTEM.ROOM_TYPE (ROOM_TYPE_ID, DESCRIPTION, MAX_CAPACITY) VALUES (1, 'Suit', 8);
INSERT INTO BOOKING_SYSTEM.ROOM_TYPE (ROOM_TYPE_ID, DESCRIPTION, MAX_CAPACITY) VALUES (2, 'Double', 5);
INSERT INTO BOOKING_SYSTEM.ROOM_TYPE (ROOM_TYPE_ID, DESCRIPTION, MAX_CAPACITY) VALUES (3, 'Single', 3);