INSERT INTO BOOKING_SYSTEM.ROOM (ROOM_ID, NUMBER, NAME, STATUS, SMOKE, ROOM_TYPE_ID) VALUES (2, 'A1', 'First Floor Suit', 'open', false, 1);
INSERT INTO BOOKING_SYSTEM.ROOM (ROOM_ID, NUMBER, NAME, STATUS, SMOKE, ROOM_TYPE_ID) VALUES (3, 'A2', 'First Floor Double', 'open', false, 2);
INSERT INTO BOOKING_SYSTEM.ROOM (ROOM_ID, NUMBER, NAME, STATUS, SMOKE, ROOM_TYPE_ID) VALUES (4, 'A3', 'First Floor Double', 'open', false, 2);
INSERT INTO BOOKING_SYSTEM.ROOM (ROOM_ID, NUMBER, NAME, STATUS, SMOKE, ROOM_TYPE_ID) VALUES (5, 'A4', 'First Floor Single', 'open', false, 3);
INSERT INTO BOOKING_SYSTEM.ROOM (ROOM_ID, NUMBER, NAME, STATUS, SMOKE, ROOM_TYPE_ID) VALUES (6, 'A5', 'First Floor Single', 'open', false, 3);